# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-29 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPro3', '0004_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
