# Generated by Django 2.1.3 on 2020-02-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPro3', '0008_auto_20191001_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='allowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Title_Relation', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=100)),
                ('Photo_recognition', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPro3.allowed'),
        ),
        migrations.DeleteModel(
            name='album',
        ),
    ]
